apiVersion: v1
kind: Pod
metadata:
  name: broken-04
spec:
  containers:
    - name: podinfo
      image: ghcr.io/stefanprodan/podinfo:6.15.0
      ports:
        - containerPort: "9898"
      env:
        - name: PODINFO_UI_MESSAGE
          value: 42
